### ISSUE TITLE
Zenhub unresponsive after waking laptop from sleep

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1181]
After I wake my laptop from sleep and go to the github/zenhub tab, the whole page is unresponsive. Clicking any button or card from the Zenhub interface doesn't work and doesn't do a thing. The browser tab is still alive, and I even still get mouseover or even click effects when hovering or clicking on buttons, but they just don't do anything.

One fix is to refresh the page, another fix is to browse to one of the "real" Github tabs (e.g. "Issues") which still works, and then back to "Board".

This is something I have only started to notice in the last week or so, so it's definitely a recent issue, as I am using Zenhub on a daily basis and would have noticed it before. Anything you guys released recently that could cause this behaviour? Anything related to offline mode perhaps or around connectivity to the server?

**Comment by kendramoroz** [comment]
@adamreisnz thanks for sending this through—seems like there's something unintended going on here. Do you see the `disconnected` toast modal in the bottom left of the screen upon waking up your computer and or anything in the console? It'd also be helpful to know the browser/version you're working and seeing this on!

**Comment by adamreisnz** [comment]
Today I had a look after opening laptop. The disconnected dialog appeared, but disappeared quickly. Zenhub seemed to be functioning normally after that.

I'll keep an eye on it, and when it happens again I'll double check.

I'm using the latest Chrome on OS X.

**Comment by adamreisnz** [comment]
@kendramoroz I've had it happen again on my iMac this time.

The disconnect message is not present on the screen when it happens, but I got the following error in my console when I clicked on a card. This is likely the cause of the issue:

```
Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30727)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32253)
    at M.r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:525025)
    at M.r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:524380)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:708774)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:171449)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:171266)
```

**Comment by adamreisnz** [comment]
@kendramoroz any chance your dev team could prioritise this issue and deploy a hotfix?
It's really quite unworkable as I have to refresh the board multiple times a day which gets rid of all my filters etc.

**Comment by kendramoroz** [comment]
@adamreisnz I'll talk to the team about what we can do here! Stay tuned :)

**Comment by adamreisnz** [comment]
The same error appears when trying to search

**Comment by turbojones** [comment]
I've also been experiencing a frozen board after sleep. No notifications and sometimes even a refresh doesn't resolve it.

**Comment by kendramoroz** [comment]
@turbojones thanks for letting us know! Are you also operating on Chrome OS? Next time you see this behavior, it'd be great to get a screenshot of the developer console to see if you're encountering the same errors above.

**Comment by adamreisnz** [comment]
Hi @kendramoroz , any word on this? This is really super, super frustrating to have to go through every day, or multiple times per day. Can your team please prioritise this and fix this bug? The error is clearly logged in the console, so it should be easy to track down.

**Comment by kendramoroz** [comment]
@adamreisnz just pinged the team to re-discuss priority on this one. Definitely understand the frustration here. I'll update this issue once there's more granularity on a launch day for a fix on this one.

**Comment by turbojones** [comment]
It happened again today. Here's the log dump from Chrome console. Chrome/Mac env. 

`github-8048958e9b1e39d753f436553cbcbd8a898175e85fb3c24bfe08115f7e48c238.js:3 Failed to update content <div id=​"partial-discussion-sidebar" class=​"js-socket-channel js-updatable-content" data-channel=​"issue:​250405044" data-url=​"/​weblifeio/​weblifemirror/​issues/​2077/​show_partial?partial=issues%2Fsidebar">​…​</div>​ Error: element had interactions
    at Object.<anonymous> (https://assets-cdn.github.com/assets/github-8048958e9b1e39d753f436553cbcbd8a898175e85fb3c24bfe08115f7e48c238.js:3:27122)
    at n (https://assets-cdn.github.com/assets/frameworks-ba03fb306bad3cf7ca33cd0c04050fbd4da92490197e28456be7234c8a02d937.js:2:21941)
    at Generator._invoke (https://assets-cdn.github.com/assets/frameworks-ba03fb306bad3cf7ca33cd0c04050fbd4da92490197e28456be7234c8a02d937.js:2:23371)
    at Generator.e.(anonymous function) [as next] (https://assets-cdn.github.com/assets/frameworks-ba03fb306bad3cf7ca33cd0c04050fbd4da92490197e28456be7234c8a02d937.js:2:22120)
    at n (https://assets-cdn.github.com/assets/frameworks-ba03fb306bad3cf7ca33cd0c04050fbd4da92490197e28456be7234c8a02d937.js:2:21941)
    at t (https://assets-cdn.github.com/assets/frameworks-ba03fb306bad3cf7ca33cd0c04050fbd4da92490197e28456be7234c8a02d937.js:2:22201)
    at https://assets-cdn.github.com/assets/frameworks-ba03fb306bad3cf7ca33cd0c04050fbd4da92490197e28456be7234c8a02d937.js:2:22318
    at <anonymous>
(anonymous) @ github-8048958e9b1e39d753f436553cbcbd8a898175e85fb3c24bfe08115f7e48c238.js:3
main.js:56 Possibly unhandled Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:72657)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:83947
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:72005
    at Object.dispatch (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:71720)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:50:569064)
r.possiblyUnhandledRejection @ main.js:56
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:76981)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:83947
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:72005
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:71720
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:75:325642
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:76981)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:83947
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:72005
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:71720
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:75:325642
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:76981)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:83947
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:72005
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:71720
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:75:325642
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:76981)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:83947
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:72005
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:189:71720
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:75:325642
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554650)
    at r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554005)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:755914)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166877)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166694)
normalizeArgumentsAndValidate @ VM34 extensions::schemaUtils:112
self.(anonymous function) @ VM47 extensions::StorageArea:35
get @ ChromeAPI.js:18
o @ main.js:39
t.trackMPEvent @ main.js:39
_regularLoadIssueViewer @ main.js:70
loadIssueViewer @ main.js:70
r @ main.js:70
value @ main.js:70
value @ main.js:70
r @ main.js:56
s @ main.js:56
a @ main.js:56
f @ main.js:50
m @ main.js:50
r @ main.js:70
processEventQueue @ main.js:50
r @ main.js:75
handleTopLevel @ main.js:75
o @ main.js:75
perform @ main.js:50
batchedUpdates @ main.js:75
o @ main.js:44
dispatchEvent @ main.js:75
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554650)
    at r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554005)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:755914)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166877)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166694)
normalizeArgumentsAndValidate @ VM34 extensions::schemaUtils:112
self.(anonymous function) @ VM47 extensions::StorageArea:35
get @ ChromeAPI.js:18
o @ main.js:39
t.trackMPEvent @ main.js:39
_regularLoadIssueViewer @ main.js:70
loadIssueViewer @ main.js:70
r @ main.js:70
value @ main.js:70
value @ main.js:70
r @ main.js:56
s @ main.js:56
a @ main.js:56
f @ main.js:50
m @ main.js:50
r @ main.js:70
processEventQueue @ main.js:50
r @ main.js:75
handleTopLevel @ main.js:75
o @ main.js:75
perform @ main.js:50
batchedUpdates @ main.js:75
o @ main.js:44
dispatchEvent @ main.js:75
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554650)
    at r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554005)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:755914)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166877)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166694)
normalizeArgumentsAndValidate @ VM34 extensions::schemaUtils:112
self.(anonymous function) @ VM47 extensions::StorageArea:35
get @ ChromeAPI.js:18
o @ main.js:39
t.trackMPEvent @ main.js:39
_regularLoadIssueViewer @ main.js:70
loadIssueViewer @ main.js:70
r @ main.js:70
value @ main.js:70
value @ main.js:70
r @ main.js:56
s @ main.js:56
a @ main.js:56
f @ main.js:50
m @ main.js:50
r @ main.js:70
processEventQueue @ main.js:50
r @ main.js:75
handleTopLevel @ main.js:75
o @ main.js:75
perform @ main.js:50
batchedUpdates @ main.js:75
o @ main.js:44
dispatchEvent @ main.js:75
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554650)
    at r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554005)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:755914)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166877)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166694)
normalizeArgumentsAndValidate @ VM34 extensions::schemaUtils:112
self.(anonymous function) @ VM47 extensions::StorageArea:35
get @ ChromeAPI.js:18
o @ main.js:39
t.trackMPEvent @ main.js:39
_regularLoadIssueViewer @ main.js:70
loadIssueViewer @ main.js:70
r @ main.js:70
value @ main.js:70
value @ main.js:70
r @ main.js:56
s @ main.js:56
a @ main.js:56
f @ main.js:50
m @ main.js:50
r @ main.js:70
processEventQueue @ main.js:50
r @ main.js:75
handleTopLevel @ main.js:75
o @ main.js:75
perform @ main.js:50
batchedUpdates @ main.js:75
o @ main.js:44
dispatchEvent @ main.js:75
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554650)
    at r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554005)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:755914)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166877)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166694)
normalizeArgumentsAndValidate @ VM34 extensions::schemaUtils:112
self.(anonymous function) @ VM47 extensions::StorageArea:35
get @ ChromeAPI.js:18
o @ main.js:39
t.trackMPEvent @ main.js:39
_regularLoadIssueViewer @ main.js:70
loadIssueViewer @ main.js:70
r @ main.js:70
value @ main.js:70
value @ main.js:70
r @ main.js:56
s @ main.js:56
a @ main.js:56
f @ main.js:50
m @ main.js:50
r @ main.js:70
processEventQueue @ main.js:50
r @ main.js:75
handleTopLevel @ main.js:75
o @ main.js:75
perform @ main.js:50
batchedUpdates @ main.js:75
o @ main.js:44
dispatchEvent @ main.js:75
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30935)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32461)
    at r._regularLoadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554650)
    at r.loadIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:554005)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:755914)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166877)
    at t.value (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:166694)
normalizeArgumentsAndValidate @ VM34 extensions::schemaUtils:112
self.(anonymous function) @ VM47 extensions::StorageArea:35
get @ ChromeAPI.js:18
o @ main.js:39
t.trackMPEvent @ main.js:39
_regularLoadIssueViewer @ main.js:70
loadIssueViewer @ main.js:70
r @ main.js:70
value @ main.js:70
value @ main.js:70
r @ main.js:56
s @ main.js:56
a @ main.js:56
f @ main.js:50
m @ main.js:50
r @ main.js:70
processEventQueue @ main.js:50
r @ main.js:75
handleTopLevel @ main.js:75
o @ main.js:75
perform @ main.js:50
batchedUpdates @ main.js:75
o @ main.js:44
dispatchEvent @ main.js:75
`

**Comment by azenMatt** [comment]
Thanks @turbojones , that is very useful - this is in our current sprint for the team to look at so we should have some updates coming soon.

**Comment by azenMatt** [comment]
As an update here, it looks like this is tied to the extension updated while the board is in sleep mode. 

We are working on a solution and will keep you updated

**Comment by adamreisnz** [comment]
Thanks @azenMatt , however I'm not sure if @turbojones issue is the same as the one I reported. In my case, I don't get a bunch of extension errors in the console.

**Comment by azenMatt** [comment]
@Mathieuu - any thoughts on the above? 

Will the fix you have been looking at resolve both of these?

**Comment by Mathieuu** [comment]
This error: `Uncaught Error: Invocation of form` comes from Chrome not being able to access localStorage. The only way I know to reproduce that is by triggering an extension update.

I will push a fix for that specific error to production today or tomorrow. I think that should fix it.

**Comment by adamreisnz** [comment]
Awesome, thanks @Mathieuu , much appreciated.
It triggers for me every time I close the lid of my laptop and then reopen it and go back to Zenhub. Seems like it's trying to read from localstorage then perhaps to reload settings, but fails.

**Comment by Mathieuu** [comment]
ZenHub Version 2.35.3 has been released this morning. It should fix the problem.

Please tell me if that's not case.

**Comment by Mathieuu** [comment]
ZenHub Version 2.35.3 has been released this morning. I believe it should fix your problem.

Please tell me if that's not case.

**Comment by adamreisnz** [comment]
I will give it a go and see

**Comment by turbojones** [comment]
Running 2.35.7 and got this after sleep mode:

`main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:86547)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:88073)
    at r._loadNewIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:560672)
    at v (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:843557)
    at Object.r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:170207)
    at s (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:166291)
    at Object.a [as executeDispatchesInOrder] (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:166506)
main.js:56 Uncaught Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:18:36)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:86547)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:88073)
    at r._loadNewIssueViewer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:560672)
    at v (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:843557)
    at Object.r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:170207)
    at s (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:166291)
    at Object.a [as executeDispatchesInOrder] (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:166506)
`

**Comment by adamreisnz** [comment]
What action did you try to do after sleep?

I put my laptop to sleep and it seems to have worked ok now, but will want to test this a bit more.

I am seeing some other errors, which I will raise another issue for.

**Comment by turbojones** [comment]
I used the Release filter button first. Everything was unresponsive.

**Comment by Mathieuu** [comment]
Is it possible that your tab was opened when using a version < 2.35.7 (which does not contain the fix)? In that case, the code from that buggy version is still running in that tab.

**Comment by adamreisnz** [comment]
Yeah today I opened my laptop and I didn't encounter this issue anymore. Looks like it's been fixed, so I think this issue can be closed. Maybe @turbojones is experiencing another issue?

**Comment by turbojones** [comment]
It hasn't happened again yet with the newest version. I could have had the old version cached. I'll post if it recurs.

**Comment by azenMatt** [comment]
Thanks for confirming everyone, i'l close for now - but please reopen / let me know if it comes back and we will take another look at it.
