### ISSUE TITLE
Unhandled rejection error

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1228]
```
Possibly unhandled Error: [object Object]
    at Object.o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:83582)
    at Object.<anonymous> (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:7709)
    at d (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:6336)
    at Object.add [as fail] (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:6642)
    at Array.<anonymous> (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:7686)
    at Function.each (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:19:13405)
    at Object.<anonymous> (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:7619)
    at Function.Deferred (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:8213)
    at Object.then (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:7595)
    at s (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:83769)
```

This came up a few times in console when opening an issue

**Comment by adamreisnz** [comment]
Seems to be resolved now
