### ISSUE TITLE
ZenHub does not auto update at all (both extension and full page, edge and chrome)

### ISSUE THREAD

**Issue by Licho1** [ZenHubIO/support#1254]
Board remains mostly static until forced to reload with F5.

```
content.js:6 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com".

(anonymous) @ content.js:6
formapps.js:11 22:42:21 FACE extension version: 2.5.0.27
formapps.js:11 22:42:21 FACE extension setting: debug ON
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30588)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32114)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1208745)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1219410
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1205826
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1205541
    at dispatch (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:75:312169)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at Object.t.identifyWithZenHubID (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:77985)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:31203
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:27886)
    at e._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112413)
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112582)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:114823)
    at r._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:44:111487)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at Object.t.updateLastSeen (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:77079)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:31229
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:27886)
    at e._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112413)
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112582)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:114823)
    at r._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:44:111487)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:189 Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
sendMessage @ ChromeAPI.js:189
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:76265)
    at Object.t.track (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:77561)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:31305
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:27886)
    at e._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112413)
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112582)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:114823)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at o (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:30588)
    at Object.t.trackMPEvent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:32114)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1208745)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1219410
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1205826
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:70:1205541
    at dispatch (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:75:312169)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at Object.t.identifyWithZenHubID (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:77985)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:31203
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:27886)
    at e._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112413)
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112582)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:114823)
    at r._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:44:111487)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at Object.t.updateLastSeen (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:77079)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:31229
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:27886)
    at e._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112413)
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112582)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:114823)
    at r._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:44:111487)
swallowStorageSyncErr @ ChromeAPI.js:3
ChromeAPI.js:189 Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
sendMessage @ ChromeAPI.js:189
ChromeAPI.js:3 Swallow Chrome Storage Sync Error:  Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
    at normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at Object.get (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/utils/ChromeAPI.js:31:38)
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:76265)
    at Object.t.track (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:77561)
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:31305
    at r (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:39:27886)
    at e._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112413)
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:112582)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:56:114823)
```

**Comment by kendramoroz** [comment]
@Licho1 Kendra here! Would you be able to provide a bit more context about the issue you're experiencing? What actions are you doing when you're experiencing issues?

**Comment by Licho1** [comment]
I have kanban display open, either here:
https://app.zenhub.com/workspace/o/licho1/recognid-frauds/boards?repos=102361501
or here:
https://github.com/Licho1/recognid-frauds#boards?repos=102361501
Now when I for example create new issue (using new isuse button), or close existing issue, kanban display does not react. 
When someone else, on their computer assigns a ticket to themselves, again, kanban does not update.
I have to press F5 to reload the page completely to refresh it.

Meanwhile, similar bugs appear in console, which might or might not be related to the actual issue of kanban not updating.

**Comment by Licho1** [comment]
Few more notes that might be related:

- I have added zenhub to github, then removed it and then added it again
- i was trying to rename one pipeline to "IN PROGRESS", zenhub was claiming it already exists (which wasn't true), force the change by first renaming it to dummy and then IN PROGRESS
- the same zenhub board does not update for my friends who use it either

**Comment by kendramoroz** [comment]
@Licho1 thanks for the additional notes! Would you be able to send an email to support@zenhub.com with your timezone and a few times that work to jump into a support call to continue debugging here?
