### ISSUE TITLE
Epics are not loading

### ISSUE THREAD

**Issue by citizenklem** [ZenHubIO/support#1270]
When creating an issue, it's now been 2 weeks that we cannot link it to any already created epic.

**Comment by azenMatt** [comment]
Hi @citizenklem - that sounds strange, would you be able to share any screenshots of what this looks like? 

Additionally, when opening the epic selector, do you get any error messages in your browser console? 

(on chrome, this is view -> developer -> javascript console -> errors)

**Comment by kendramoroz** [comment]
@citizenklem Hey Clem, following up on this issue! Are you still experiencing Epics not loading?

**Comment by balat** [comment]
Some more information on our epic problem:

When trying to set an epic to an issue, I see these error messages in the browser console:

```
GET https://api.zenhub.io/v4/repositories/80415520/epics 400 (Bad Request)
vendor.edc29cf910c2a1067213.js:89187 Possibly unhandled Error: [object Object]
    at Object.Promise$_rejectFromThenable (https://app.zenhub.com/dist/vendor.edc29cf910c2a1067213.js:92921:40)
    at Object.<anonymous> (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8418:41)
    at fire (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8264:31)
    at Object.add [as fail] (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8311:13)
    at Array.<anonymous> (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8417:33)
    at Function.each (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:6006:30)
    at Object.<anonymous> (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8413:20)
    at Function.Deferred (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8471:14)
    at Object.then (https://app.zenhub.com/dist/index.54ee341ba554603b4f76.js:8412:25)
    at Promise$_doThenable (https://app.zenhub.com/dist/vendor.edc29cf910c2a1067213.js:92885:14)
```
The request which fails with error 400 returns:
```
{"message":"Error response from GitHub API"}
```

Hope this helps ...

**Comment by jrochel** [comment]
```
Possibly unhandled o@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:125028
Deferred/then/</</<@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:7707
d@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:6331
add@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:6642
Deferred/then/</<@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:7679
each@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:19:13403
Deferred/then/<@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:7616
Deferred@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:8211
then@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:39:7592
s@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:125213
i@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:124750
e.exports/e.prototype._settlePromiseFromHandler@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:100313
e.exports/e.prototype._settlePromiseAt@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:102372
e.exports/e.prototype._settlePromises@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:104597
e.exports/e.prototype._rejectPromises@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:104466
r.prototype._consumeFunctionBuffer@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:127549
r/this.consumeFunctionBuffer@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:126923
u.prototype.run@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:90799
a@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:90307
main.js:56:79170
Possibly unhandled e.exports/e.prototype._settlePromiseFromHandler@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:100232
e.exports/e.prototype._settlePromiseAt@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:102372
e.exports/e.prototype._settlePromises@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:104597
e.exports/e.prototype._rejectPromises@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:56:104466
r.prototype._consumeFunctionBuffer@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:127549
r/this.consumeFunctionBuffer@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:126923
u.prototype.run@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:90799
a@moz-extension://3d72d5ad-552f-4a85-8787-c4abf2e97aa9/js/built/main.js:44:90307
main.js:56:79170
```

Frankly this needs to be fixed. This is the key feature of ZenHub and it hasn't been working for months1

**Comment by kendramoroz** [comment]
Hey team - thanks for the ping and apologies that this is still an issue for some of you. I've pinged the team once more to dig in here - we'll be in touch if we need any additional debugging support. We're on-top of debugging, so I'll post updates once we have more to share on the cause 🙏

**Comment by kendramoroz** [comment]
👋 hey everyone! Thanks for your patience here. The team has discovered what's going on! It seems that this error is caused when **one of the Epics on your Board contains issues from a different repo where Issues have been disabled in GitHub**. If a repo that is connected has Issues disabled, ZenHub is not able to fetch them from GitHub, generating an error and inability to use the Epics menu.

To fix the problem, you can re-enable issues in every repo where Issues will be added to Epics in your connected Board. Alternatively, removing those Issues from the Epics should fix the issue and allow you to re-disable Issues in those repos without error this time if you need to keep Issues disabled.

To enable Issues once more, click on Settings for the repo then make sure Issues is checked like below:

![image](https://user-images.githubusercontent.com/11036230/34579325-5de7318a-f13d-11e7-9b0e-817fc35673d3.png)


Once doing this if anyone experiences errors still, please let me know!

**Comment by balat** [comment]
Done. Thanks a lot!
