### ISSUE TITLE
Issue creation failed: 404 Not Found when using Quick Issue Creator within Epic Builder

### ISSUE THREAD

**Issue by cappadona** [ZenHubIO/support#658]
Hi team...love the new epics just rolled out with `v2.16.11`. I'm getting this 404 Error when using the Quick Issue Creator as described in your [blog post](https://www.zenhub.io/blog/working-with-epics-in-github).

I get the same results in both Chrome and Firefox and have also attempted to reboot my machine as well. Is this a known issue?

Here's what I'm seeing in the console:

```js
POST https://api.github.com/repos/**redactedOwner**/**redactedRepo**/issues 404 (Not Found)
XHR finished loading: POST "https://api.github.com/repos/**redactedOwner**/**redactedRepo**/issues".
Possibly unhandled Error: [object Object]
    at e._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:6:28475)
    at e._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:6:30630)
    at e._settlePromises (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:7:851)
    at e._rejectPromises (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:7:720)
    at i._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:7:7474)
    at consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:7:6839)
    at s.run (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:7:2943)
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:7:2577)
```

**Comment by Mathieuu** [comment]
The issue will be created in the repository selected in the filter. Could you make sure that you have access to that repo and that you can create an issue in that repository ?

**Comment by cappadona** [comment]
Thanks. Yes, I have full access (admin permission level) to the repo in question and have no trouble creating issues outside of the Quick Issue Creator.

**Comment by Mathieuu** [comment]
Could you shoot an email to support@zenhub.io with the organization and repository name ? That would help us a lot to troubleshoot your issue.

**Comment by cappadona** [comment]
Email sent. Thanks!

**Comment by cappadona** [comment]
Hi Mathieu, I followed the steps [here](https://www.zenhub.io/organizationFAQ) as you suggested via email and we're back in business. Thanks!!!
