### ISSUE TITLE
JS error when loading Burndown

### ISSUE THREAD

**Issue by moskovich** [ZenHubIO/support#952]
I am running Chrome (extension v. 2.24.26) and get the following error:

```
main.js:7 Possibly unhandled TypeError: Cannot read property 'title' of undefined
    at i (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:61:27760)
    at a.configureFinalMapState (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:47:26309)
    at a.computeStateProps (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:47:26101)
    at a.updateStatePropsIfNeeded (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:47:27059)
    at a.render (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:47:29574)
    at d._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:27:13945)
    at d._renderValidatedComponent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:27:14033)
    at d.performInitialMount (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:27:9939)
    at d.mountComponent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:27:8988)
    at Object.mountComponent (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:25:14358)
```

**Comment by azenMatt** [comment]
Thanks for reporting this @moskovich 

Does this create any functionality problems for you?

**Comment by moskovich** [comment]
Before it stopped all loading. But it seems to be fixed now. I'll close the bug as I'm no longer having the issue.
